### ISSUE TITLE
VN

### ISSUE THREAD

**Issue by June24-optimize** [VLOGroup/mri-variationalnetwork#3]
In the train_mri_vn.py, line 155, vn.setupLogDirs(suffix, args, checkpoint_config).
Here, the file "vn" does not have the  module named "setupLogDirs".

**Comment by khammernik** [comment]
The package `vn` includes everything from the package files, i.e., `utils.py`, `data.py`, in its initialization file `__init__.py`. Therefore, `vn.setupLogDirs(...)` can be accessed directly although it is defined in `utils.py`.
