### ISSUE TITLE
No module named 'tensorflow.contrib.icg'

### ISSUE THREAD

**Issue by HatDu** [VLOGroup/mri-variationalnetwork#5]
I find this error when I was reading code. And I looked up in the tensorflow api, the result image shows blow. I am not familiar with tensorflow could someone help me?

**train_mri_vn.py**
```
import tensorflow.contrib.icg as icg

class VnMriReconstructionCell(tf.contrib.icg.VnBasicCell):
    def mriForwardOpWithOS(self, u, coil_sens, sampling_mask):
```
![image](https://user-images.githubusercontent.com/22195777/63855931-2191da80-c9d3-11e9-8d6a-70323eb12933.png)

**Comment by khammernik** [comment]
The extension `contrib.icg` is not part of the original tensorflow framework. As stated in the Readme, the code requires to build the modified [tensorflow-icg](https://github.com/VLOGroup/tensorflow-icg) framework from source.

**Comment by HatDu** [comment]
Ok and thanks!
