### ISSUE TITLE
Hi, you can access most of the data here: http://mridata.org/list?project=NYU%20machine%20learning%20data

### ISSUE THREAD

**Issue by adityarastogi2k12** [VLOGroup/mri-variationalnetwork#9]
Hi, you can access most of the data here: http://mridata.org/list?project=NYU%20machine%20learning%20data

Hi jtamir, I downloaded the .h5 files but I am not able to navigate myself to the kspace or image data in that file. Can you please tell me that under which "member" the kspace or image data is presents

Regards
Aditya Rastog

**Comment by khammernik** [comment]
Closed as the data loading in this repository supports loading from the `*.mat` files provided in Globus.
